### ISSUE TITLE
Release version 1.2.0

### ISSUE THREAD

**Issue by kairoaraujo** [kairoaraujo/goca#12]
- Prepare the release notes
- Release version 1.2.0 and new Docker Images

**Comment by kairoaraujo** [comment]
I will be working on the new release.
Is there anything else @necheffa you would like to have before it goes out?

**Comment by necheffa** [comment]
@kairoaraujo I think we have plenty to make a 1.2.0 release.

**Comment by kairoaraujo** [comment]
https://pkg.go.dev/github.com/kairoaraujo/goca
